### ISSUE TITLE
question: how to access Model methods from schema methods?

### ISSUE THREAD

**Issue by langfors** [gradecam/mongoose-decorators-ts#1]
If I'm writing a schema instance method which needs to run a Model method, e.g. `save()`, what is the best way to access these mongoose methods?  Thanks

**Comment by jloveridge** [comment]
I will update the todo sample to demonstrate this but it can be accomplished simply by doing something like the following:

```typescript
// the rest of the implementation remains as shown in the example
export class TodoSchema {
  async updateDueDate(this: Todo, dueAt: Date) {
    this.dueAt = dueAt;
    await this.save();
  }
}
```
